name: ci
on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: read
  issues: write         # hiding bot comments
  pull-requests: write  # hiding bot comments

jobs:
  test:
    uses: alpine-ros/alpine-ros-ci-workflows/.github/workflows/ros1.yaml@main
    with:
      enable-bot-comment: true
      bot-comment-api-base: "https://ghbot-api.at-wat.tokyo"
    secrets:
      bot-comment-token: "3d1bc7c1-21ac-4a3f-a852-6f79a7b0a3fe"
